/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_demo_ndkdemo_MainActivity */

#ifndef _Included_example_demo_ndkdemo_MainActivity
#define _Included_example_demo_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_demo_ndkdemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_demo_ndkdemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
